# Generated by Django 3.0.2 on 2020-01-12 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='songs',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
