# Generated by Django 3.0.2 on 2020-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200112_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='lyrics',
            field=models.TextField(),
        ),
    ]
