# Generated by Django 3.0.2 on 2020-01-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200112_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(default='', upload_to='songs'),
        ),
    ]
