# Generated by Django 3.0.2 on 2020-01-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200112_1228'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='songs',
            table='Songs',
        ),
    ]
