# Generated by Django 3.0.2 on 2020-01-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200112_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='is_favorite',
        ),
    ]
