# Generated by Django 3.0.2 on 2020-01-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200112_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.Album'),
        ),
    ]
